### ISSUE TITLE
gatling:execute fails

### ISSUE THREAD

**Issue by davechesebrough** [gatling/gatling-maven-plugin-demo#10] opened 2015-10-28 21:29 UTC
The command $ mvn gatling:execute -Dgatling.simulationClass=comuterdatabase.BasicSimulation runs the simulation successfully.

FYI, getting the following Maven output when attempting the shorthand, $mvn gatling:execute

$ mvn gatling:execute
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building gatling-maven-plugin-demo 2.1.7
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- gatling-maven-plugin:2.1.7:execute (default-cli) @ gatling-maven-plugin-demo ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.644 s
[INFO] Finished at: 2015-10-28T17:26:13-04:00
[INFO] Final Memory: 9M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.gatling:gatling-maven-plugin:2.1.7:execute (default-cli) on project gatling-maven-plugin-demo: Gatling failed. java.lang.IllegalStateException: basedir /Users/davechesebrough/Code/gatling-maven-plugin-demo/target/test-classes does not exist -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

I can add the missing directory but I get the following:

Gatling failed. No simulations to run

**Comment by slandelle** [comment] 2015-10-29 07:30
Can't reproduce.
Did you edit the log `/Users/....../gatling-maven-plugin-demo/target/test-classes`?
If so, what does it actually look like? Is there some symlink or other weird things in the path?

**Comment by davechesebrough** [comment] 2015-10-29 12:21
I did, sorry if that was unclear - no symlinks, for all intents and purposes, it is `/Users/davechesebrough/Code/gatling-maven-plugin-demo`

**Comment by slandelle** [comment] 2015-10-29 12:36
Running with a shell emulator (git cli, cygwin) maybe?

I really can't reproduce.

**Comment by davechesebrough** [comment] 2015-10-29 12:37
OSX El Capitan terminal. Couldn't reproduce on a different MacBook either, though.

Thanks for looking into it - will update if I figure out what's going on. Must be a configuration issue on my end then :)

**Comment by slandelle** [comment] 2015-10-29 12:39
Thanks. I'm closing for now. Please feel free to ping if you find anything on the Gatling side.

**Closed by slandelle** 2015-10-29 12:39 UTC
